version: '2'

networks:
  demo-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    expose:
     - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - demo-tier
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9082:9082'
      - '9094:9094'
    expose:
      - '9092'
      - '9082'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: INSIDE://kafka:9094,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9094,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes" 
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    networks:
      - demo-tier
  pyproducer:
    build: ./pyproducer/
    depends_on:
      - kafka
    networks:
      - demo-tier
  pyconsumer:
    build: ./pyconsumer/
    depends_on:
      - mysqldb
    networks:
      - demo-tier
  elk:
    build: './elk/'
    ports:
      - '5601:5601'
      - '5044:5044'
      - '9200:9200'
      - '9300:9300'
    expose:
      - '5601'
      - '5044'
      - '9200'
      - '9300'
    depends_on:
      - pyproducer
    networks:
      - demo-tier
  kibana-check:
    build: './kibana-check/'
    depends_on:
      - elk
    networks:
      - demo-tier
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: demo_user
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_user
      MYSQL_DATABASE: demodb
    depends_on:
      - pyproducer
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - demo-tier